### PR TITLE
Update playnite-plugincommon submodule

### LINKED ISSUE #344: PSN user is not authenticated
Im sure it's already authenticated but still get this error

### LINKED ISSUE #350: PSN Not Working!
@Lacro59 Are you working on a new update to fix the bug in this theme?: https://github.com/Lacro59/playnite-successstory-plugin/issues/344 

Thank you very much and I really admire your effort and work.

### PR DESCRIPTION
**Pull request by damirarh**
I missed support for PSN trophies in SuccessStory so much that I decided to take a closer look at why they aren't working. I tracked the problem down to PSN authentication changes as [documented in the unofficial documentation](https://andshrew.github.io/PlayStation-Trophies/).

But as I wanted to update the code, I noticed that the changes are already applied in the [playnite-plugincommon repository](https://github.com/Lacro59/playnite-plugincommon) so I only had to update the submodule in this repository to get PSN trophies working again.

I still decided to create this PR. Perhaps it will encourage you to release an update with the fix sooner.

Fixes #344, fixes #350

### CODE REVIEW

**Comment by eskypi** [comment]
Hopefully @Lacro59  will release version 3.2 fixing this problem

**Comment by jpmckane** [comment]
> I missed support for PSN trophies in SuccessStory so much that I decided to take a closer look at why they aren't working. I tracked the problem down to PSN authentication changes as [documented in the unofficial documentation](https://andshrew.github.io/PlayStation-Trophies/).
> 
> But as I wanted to update the code, I noticed that the changes are already applied in the [playnite-plugincommon repository](https://github.com/Lacro59/playnite-plugincommon) so I only had to update the submodule in this repository to get PSN trophies working again.
> 
> I still decided to create this PR. Perhaps it will encourage you to release an update with the fix sooner.
> 
> Fixes #344, fixes #350

damirah, I'm new to this, how do I update the submodule?

**Comment by damirarh** [comment]
> I'm new to this, how do I update the submodule?

@jpmckane I assume you want to get a working extension for yourself? You could download the code from [my branch](https://github.com/damirarh/playnite-successstory-plugin/tree/fix/psn-authentication), build it in [Visual Studio Community](https://visualstudio.microsoft.com/free-developer-offers/) and copy the build output over the plugin files in your Playnite Extensions folder.

**Comment by eskypi** [comment]
I don't understand anything about programming, I don't even know how to use that program. Is there a way to download a working ".pext" version or get already compiled files so you just have to replace them in the extension folder.

**Comment by Taramur** [comment]
Maybe the creator can provide a brief assessment of when there will be an update.

**Comment by eskypi** [comment]
I'm afraid the extension is dead in updates, it's been months with the same problem with psn trophies. Is there any other extension for trophy tracking?

**Comment by Taramur** [comment]
Well maybe we take that .zip or .pext file... would really like to see this work again.

**Comment by damirarh** [comment]
This fix is already incorporated in the new 3.1.1 release. Unfortunately, that version introduces a new showstopping bug for PSN trophies (#375), but there's already a PR (#376) with a fix for that.

**Pull request closed without merging**
